version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./mileto.sql:/docker-entrypoint-initdb.d/mileto.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PosSql2680Hax
      POSTGRES_DB: mileto
    ports:
      - 5433:5432
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=mileto.com.co # O tu IP pública si no tienes dominio 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # El archivo con tu configuración personalizada
      - static:/code/staticfiles # El mismo volumen usado por Django para servir archivos estáticos
    depends_on:
      - web
    

volumes:
  postgres_data:
  static:
  media: