version: '3'

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PosSql2680Hax
      - POSTGRES_DB=mileto
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:PosSql2680Hax@db:5432/mileto
      - DEBUG=1
      - SECRET_KEY=some_secret_key
    volumes:
      - static:/app/staticfiles
      - media:/app/mediafiles
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=200.16.119.236 # O tu IP pública si no tienes dominio 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # El archivo con tu configuración personalizada
      - static:/app/staticfiles # El mismo volumen usado por Django para servir archivos estáticos
    depends_on:
      - web

volumes:
  db_data:
  static:
  media:
  certs: