# Generated by Django 4.1.2 on 2022-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Temperature', models.FloatField()),
                ('Dew_Point', models.FloatField()),
                ('Humidy', models.FloatField()),
                ('Wind_Speed', models.FloatField()),
                ('Wind_Gust', models.FloatField()),
                ('Pressure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather_track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Last_Date', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
